version: '3.8'

services:
  sms-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-your_twilio_account_sid}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-your_twilio_auth_token}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER:-your_twilio_phone_number}
      - ADMIN_KEY=${ADMIN_KEY:-sms-app-admin-2025}
      - LOG_ACCESS_SECRET=${LOG_ACCESS_SECRET:-sms-log-secret-2025-secure}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge